### ISSUE TITLE
ceil, floor, round should be Number -> Int

### ISSUE THREAD

**Issue by EugeneN** [purescript/purescript-math#7]
ceil, floor, round should be Number -> Int ?

**Comment by garyb** [comment]
Unfortunately not, as `Int`s are restricted to a 32 bit range (in the JS backend at least), but `ceil`, `floor`, and `round` can deal with integers-as-`Number` between `-9,007,199,254,740,991` and `9,007,199,254,740,991`.

**Comment by EugeneN** [comment]
well how can one convert Number to Int then?

**Comment by garyb** [comment]
https://github.com/purescript/purescript-integers/blob/master/docs/Data/Int.md#fromnumber

**Comment by sharkdp** [comment]
I think this can be closed.
