### ISSUE TITLE
Generalize max, min

### ISSUE THREAD

**Issue by ThomasCrvsr** [purescript/purescript-math#8]
Because those functions have the signature `Number -> Number -> Number` and I worked with Int, I found myself reimplementing this function for Int.

Maybe I missed an obvious trick, but should it be possible to implement those functions for types which implements `Ord` typeclass ?

**Comment by paf31** [comment]
`Math` is meant to be low-level, so I think this would be better in a `purescript-orders` package or something along those lines, but we can definitely generalize.

**Comment by ThomasCrvsr** [comment]
Yep, I agree. Do you see other functions we could add to this future package ?

**Comment by garyb** [comment]
There's an entire other class that could go in there actually, `Poset`, for partial orders.

I thought we had a `min` and `max` in foldable-traversable too actually, but I guess not!

**Comment by sharkdp** [comment]
I think this can be closed, solved by [Data.Ord.max](https://github.com/purescript/purescript-orders/blob/master/docs/Data/Ord.md#max) and min.
